Implement: app global context class
loomi/flutter-leap pull request #32
Opened 2023-08-17 20:51 UTC by ItaloDias-stack

**Changes:**

**1. What i did:**

- I've implemented a class to use global context in app

**2. What to test:**

- [ ] Layout on different devices ([mockup](link_to_mockup))
- [ ] Happy path
- [ ] Error handling

---

**How to get there**

**1. Flavor and login informations**

> **flavor**: staging
>
> **login**: loomi
>
> **password**: 12345678

**2. Steps**

- Use the "AppGlobalContext" navigator functions

---

**Observations:**

**1. Code review pratices**

- Unecessary prints/log (ctrl+f -> [ print( ] )
- Unecessary comments (ctrl+f -> [ // ] )
- Code organization
- Naming of functions and variables
- Repeated code

2023-08-18 00:31 UTC, lucasvps approved these changes

2023-08-18 14:24 UTC, arkaisho requested changes

2023-08-18 14:24 UTC, arkaisho commented on lib/src/utils/app_global_context.dart
> +    appKey.currentState!.pushNamed(routeName);
É legal manter a opção de receber um retorno das rotas chamadas usando tipos genéricos e funções assincronas assim como o flutter declara:
![image](https://github.com/loomi/flutter-leap/assets/38983117/0af34a43-008f-4363-a26a-0637abb19c9f)

2023-08-18 14:24 UTC, arkaisho commented on lib/src/utils/app_global_context.dart
> +    appKey.currentState!.pushNamed(routeName);
Para casos onde é preciso executar uma função após o fechamento de uma tela, e até mesmo com o retorno daquela tela (fazer isso para as outras funções também)

2023-08-18 14:24 UTC, arkaisho commented on lib/src/utils/app_global_context.dart
> +  static void push(String routeName) {
```suggestion
  static void pushNamed(String routeName) {
```

2023-08-23 17:24 UTC, arkaisho approved these changes

2023-08-23 17:56 UTC, merged